Repository react-native-elements/react-native-elements, pull requests merged in 2018-05, with the labels that each got.

#1159 Add Cancel Button Props Object for iOS
  docs/searchbar.md
  package-lock.json
  src/badge/badge.js
  src/helpers/nodeType.js
  src/input/Input.js
  src/list/ListItem.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/SearchBar-default.js
  website/yarn.lock
Labels: ✨Enhancement

#1167 Doc improvement: remove duplicate item
  website/versioned_docs/version-0.19.0/button.md
Labels: :book: Docs, 💊 Bug Fix

#1170 Apply renderNode for Button
  docs/button.md
  src/buttons/Button.js
  src/index.d.ts
Labels: ✨Enhancement

#1171 docs(website): Add Troubleshooting section
  .prettierrc
  docs/troubleshooting.md
  website/i18n/en.json
  website/sidebars.json
  website/versioned_docs/version-0.19.0/troubleshooting.md
  website/versioned_sidebars/version-0.19.0-sidebars.json
  website/versioned_sidebars/version-1.0.0-beta2-sidebars.json
  website/versioned_sidebars/version-1.0.0-beta3-sidebars.json
  website/versioned_sidebars/version-1.0.0-beta4-sidebars.json
Labels: :book: Docs

#1175 Doc improvement: fix url hash conflict
  website/versioned_docs/version-0.19.0/lists.md
Labels: :book: Docs

#1174 (ListItem) Customize padding with pad prop
  docs/listitem.md
  package-lock.json
  src/index.d.ts
  src/list/ListItem.js
  src/list/__tests__/__snapshots__/ListItem.js.snap
Labels: ✨Enhancement

#1185 fix: onClear for default searchbar
  src/searchbar/SearchBar-default.js
Labels: 💊 Bug Fix

#1191 Fix: Allow users to override TouchableComponent props.
  src/buttons/Button.js
Labels: ✨Enhancement

#1189 updated react native elements version to 0.54
  package-lock.json
  package.json
  src/badge/__tests__/__snapshots__/badge.js.snap
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/checkbox/__tests__/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/divider/__tests__/__snapshots__/Divider.js.snap
  src/header/__tests__/Header.js
  src/header/__tests__/__snapshots__/DummyNavButton.js.snap
  src/header/__tests__/__snapshots__/Header.js.snap
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/rating/__tests__/__snapshots__/Rating.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/slider/__tests__/__snapshots__/Slider.js.snap
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: ✨Enhancement

#1210 Fix Button Ripple on Android Version 21 and higher
  src/buttons/Button.js
Labels: 💊 Bug Fix

#1213 Add some tests
  .ci/setupTests.js
  package.json
  src/buttons/Button.js
  src/buttons/__tests__/Button.js
  src/buttons/__tests__/__snapshots__/Button.js.snap
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/overlay/__tests__/Overlay.js
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/rating/__tests__/__snapshots__/Rating.js.snap
  yarn.lock
Labels: 🔧 Tooling

#1211 Avatar Placeholder
  docs/avatar.md
  docs/listitem.md
  package.json
  src/avatar/Avatar.js
  src/helpers/nodeType.js
  src/helpers/renderNode.js
  src/list/ListItem.js
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  website/static/img/avatar_with_title_placeholder.gif
Labels: ✨Enhancement

#1218 Fix iOS SearchBar
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
Labels: 💊 Bug Fix

#1223 docs: `Avatar` with icon requires icon type
  website/versioned_docs/version-1.0.0-beta5/avatar.md
Labels: :book: Docs

#1222 docs: `Avatar` with icon requires icon type
  website/versioned_docs/version-0.19.0/avatar.md
Labels: :book: Docs

#1177 docs: missing icon type for Avatar
  docs/avatar.md
Labels: :book: Docs
