Repository react-native-elements/react-native-elements, pull requests merged in 2018-04, with the labels that each got.

#1000 Fix Button width (+ small refactor)
  src/buttons/Button.js
Labels: Bug Fix

#1049 Remove Text from Button if title is empty
  src/buttons/Button.js
Labels: Bug Fix

#990 Add `label` for the Input component
  docs/input.md
  src/index.d.ts
  src/input/Input.js
Labels: Enhancement, v1

#1013 New website props layout
  .gitignore
  website/versioned_docs/version-0.19.0/avatar.md
  website/versioned_docs/version-0.19.0/badge.md
  website/versioned_docs/version-0.19.0/button.md
  website/versioned_docs/version-0.19.0/button_group.md
  website/versioned_docs/version-0.19.0/card.md
  website/versioned_docs/version-0.19.0/checkbox.md
  website/versioned_docs/version-0.19.0/divider.md
  website/versioned_docs/version-0.19.0/forms.md
  website/versioned_docs/version-0.19.0/header.md
  website/versioned_docs/version-0.19.0/icon.md
  website/versioned_docs/version-0.19.0/lists.md
  website/versioned_docs/version-0.19.0/pricing.md
  website/versioned_docs/version-0.19.0/rating.md
  website/versioned_docs/version-0.19.0/searchbar.md
  website/versioned_docs/version-0.19.0/slider.md
  website/versioned_docs/version-0.19.0/social_icons.md
  website/versioned_docs/version-0.19.0/text.md
  website/versioned_docs/version-0.19.0/tile.md
  website/versioned_docs/version-1.0.0-beta2/button.md
  website/versioned_docs/version-1.0.0-beta2/button_group.md
  website/versioned_docs/version-1.0.0-beta2/input.md
  website/versioned_docs/version-1.0.0-beta2/overlay.md
  website/versioned_docs/version-1.0.0-beta2/searchbar.md
  website/versioned_docs/version-1.0.0-beta3/button.md
  website/versioned_docs/version-1.0.0-beta3/card.md
  website/versioned_docs/version-1.0.0-beta3/header.md
  website/versioned_docs/version-1.0.0-beta3/searchbar.md
Labels: Docs, Enhancement

#945 ListItem v1 (Android & iOS)
  docs/input.md
  docs/listitem.md
  docs/lists.md
  package.json
  src/divider/Divider.js
  src/divider/__tests__/__snapshots__/Divider.js.snap
  src/index.js
  src/input/Input.js
  src/list/List.js
  src/list/ListItem.js
  src/list/__tests__/List.js
  src/list/__tests__/ListItem.js
  src/list/__tests__/__snapshots__/List.js.snap
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  website/sidebars.json
  website/static/img/input_with_explanation.png
  website/static/img/input_without_explanation.png
  website/static/img/listitem_with_gradient_scale.gif
  yarn.lock
Labels: Enhancement, New Component, v1

#865 Enhanced style control to ratings
  .gitignore
  docs/rating.md
  src/rating/Rating.js
  src/rating/__tests__/__snapshots__/Rating.js.snap
Labels: Enhancement

#1056 set size of Icon or clearIcon in SearchBar
  src/searchbar/SearchBar-default.js
Labels: Enhancement

#1078 Fix typo in listitem.md
  docs/listitem.md
  website/versioned_docs/version-1.0.0-beta4/listitem.md
Labels: :book: Docs, 💊 Bug Fix

#1061 Allowed Badge to accept any component as the Container component
  src/badge/badge.js
Labels: ✨Enhancement

#1087 Button group use platform touchable
  src/buttons/ButtonGroup.js
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
Labels: ✨Enhancement

#1092 Add WeChat color to SocialIcon
  src/social/SocialIcon.js
Labels: ✨Enhancement

#1090 Fix ListItem platform checkmark size
  src/list/ListItem.js
Labels: 💊 Bug Fix

#1094 Dismiss overlay by touching overlaybackground
  docs/overlay.md
  src/index.d.ts
  src/overlay/Overlay.js
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
Labels: ✨Enhancement

#1101 Use v0.19.0 as default website version
  website/versions.json
Labels: :book: Docs

#1098 Refactor Avatar Size props
  docs/avatar.md
  src/avatar/Avatar.js
  src/index.d.ts
Labels: ✨Enhancement

#1108 Migrate raised prop back to Button component
  docs/button.md
  src/buttons/Button.js
  src/index.d.ts
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: ✨Enhancement, 🥇v1

#1135 Refactor and make uniform all SearchBars
  docs/input.md
  docs/searchbar.md
  src/helpers/nodeType.js
  src/helpers/renderNode.js
  src/input/Input.js
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/SearchBar-android.js
  src/searchbar/__tests__/SearchBar-default.js
  src/searchbar/__tests__/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: ✨Enhancement

#1156 docs(website): Set default version shown as 0.19.0
  docs/listitem.md
  website/package.json
  website/siteConfig.js
  website/versioned_docs/version-1.0.0-beta4/listitem.md
  website/yarn.lock
Labels: :book: Docs

#1151 docs(Input) Typo it should be labelStyle not labelString
  docs/input.md
  website/versioned_docs/version-1.0.0-beta4/input.md
Labels: :book: Docs, 💊 Bug Fix

#1152 Typo?
  docs/listitem.md
  website/versioned_docs/version-1.0.0-beta4/listitem.md
Labels: :book: Docs

#1113 Fix for Button and Overlay collision issue
  src/overlay/Overlay.js
Labels: 💊 Bug Fix

#1158 ci(travis) Pin version of node
  .travis.yml
Labels: 🔧 Tooling
