Repository react-native-elements/react-native-elements, pull requests merged in 2018-09, with the labels that each got.

#1401 [docs] changed ListView ( deprecated ) to FlatList
  website/versioned_docs/version-0.19.0/lists.md
Labels: :book: Docs

#1377 [deps] bump jest to fix console variable
  package.json
  src/tooltip/__tests__/__snapshots__/Tooltip.js.snap
Labels: 🔧 Tooling

#1403 docs(Card): Remove Lato fontFamily from examples
  website/versioned_docs/version-0.19.0/card.md
  website/versioned_docs/version-1.0.0-beta3/card.md
Labels: :book: Docs

#1344 Fixes props being ignored on ListItem
  src/list/ListItem.js
  src/list/__tests__/ListItem.js
  src/list/__tests__/__snapshots__/ListItem.js.snap
Labels: 💊 Bug Fix

#1409 [ListItem] Add android as default for list styling
  src/list/ListItem.js
Labels: ✨Enhancement

#1416 Add registerCustomIconType typing
  src/index.d.ts
Labels: ✨Enhancement

#1413 feat(Input): add inputComponent prop (closes #1408)
  docs/input.md
  src/index.d.ts
  src/input/Input.js
  src/input/__tests__/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
Labels: ✨Enhancement

#1410 package: Use opencollective-postinstall for smaller install size
  package.json
  yarn.lock
Labels: 🔧 Tooling, 🤔Thoughts?

#1233 Fix ListItem dividers + customs chevron & checkmark
  docs/listitem.md
  src/config/colors.js
  src/divider/Divider.js
  src/divider/__tests__/__snapshots__/Divider.js.snap
  src/index.d.ts
  src/list/ListItem.js
  src/list/__tests__/__snapshots__/ListItem.js.snap
Labels: ✨Enhancement, 💊 Bug Fix

#1433 Fix Button On Web
  src/buttons/Button.js
Labels: ✨Enhancement
