Repository react-native-elements/react-native-elements, pull requests merged in 2018-12, with the labels that each got.

#1624 Add official platform colors
  docs/customization.md
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/config/__tests__/__snapshots__/ThemeProvider.js.snap
  src/config/colors.js
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/image/__tests__/__snapshots__/Image.js.snap
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/rating/__tests__/__snapshots__/Rating.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
  src/text/__tests__/__snapshots__/Text.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: ✨Enhancement

#1556 feat(Header): Add background image
  docs/header.md
  src/header/Header.js
  src/header/__tests__/Header.js
  src/header/__tests__/__snapshots__/Header.js.snap
  src/index.d.ts
Labels: ✨Enhancement

#1644 fix(Input): Make width to be 100% instead of 90%
  src/input/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
  src/list/ListItem.js
  src/list/__tests__/ListItem.js
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: 💊 Bug Fix

#1647 fix(ListItem): Allow solo rightTitle to display correctly
  src/list/ListItem.js
  src/list/__tests__/__snapshots__/ListItem.js.snap
Labels: 💊 Bug Fix

#1657 ci(travis): Remove codecov from devDependencies
  .travis.yml
  package.json
  yarn.lock
Labels: 🔧 Tooling

#1651 Bound slider value between min and max
  src/slider/Slider.js
  src/slider/__tests__/Slider.js
  src/slider/__tests__/__snapshots__/Slider.js.snap
Labels: 💊 Bug Fix

#1659 Remove unnecessary props from Card
  docs/card.md
  src/card/Card.js
  src/card/__tests__/Card.js
  src/card/__tests__/__snapshots__/Card.js.snap
  src/index.d.ts
Labels: ✨Enhancement

#1675 fix(Text): Allow local props to override theme set font size
  src/text/Text.js
  src/text/__tests__/Text.js
  src/text/__tests__/__snapshots__/Text.js.snap
Labels: 💊 Bug Fix

#1673 update Tile docs with overlayContainerStyle prop
  docs/tile.md
Labels: :book: Docs

#1685 feat(Text): Allow style prop to accept array of objects
  src/text/Text.js
  src/text/__tests__/Text.js
Labels: 💊 Bug Fix

#1691 Update tooltip
  docs/tooltip.md
Labels: :book: Docs

#1682 [Input] Direct Manipulation
  src/index.d.ts
  src/input/Input.js
  src/input/__tests__/Input.js
Labels: ✨Enhancement

#1695 fix(types): Fix ListItem checkBox props typo
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1701 fix(SearchBar Android): Allow margins to be added to containerStyle
  src/searchbar/SearchBar-android.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: 💊 Bug Fix
