Repository react-native-elements/react-native-elements, pull requests merged in 2018-11, with the labels that each got.

#1540 feat: Add button types
  docs/button.md
  package.json
  src/buttons/Button.js
  src/buttons/__tests__/Button.js
  src/buttons/__tests__/__snapshots__/Button.js.snap
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/config/__tests__/__snapshots__/ThemeProvider.js.snap
  src/config/colors.js
  src/helpers/index.js
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/index.d.ts
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/rating/__tests__/__snapshots__/Rating.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
  src/text/__tests__/__snapshots__/Text.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
  website/static/css/components.css
  website/static/img/button/button--clear.jpg
  website/static/img/button/button--outline.jpg
  website/static/img/button/button--solid.jpg
  yarn.lock
Labels: ✨Enhancement

#1536 Fix: paragraphs links in docs
  docs/avatar.md
  docs/tooltip.md
Labels: :book: Docs

#1545 Badge refractor
  docs/badge.md
  src/badge/__tests__/__snapshots__/badge.js.snap
  src/badge/__tests__/badge.js
  src/badge/badge.js
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/config/__tests__/__snapshots__/ThemeProvider.js.snap
  src/config/colors.js
  src/helpers/renderNode.js
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/index.d.ts
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/rating/__tests__/__snapshots__/Rating.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
  src/text/__tests__/__snapshots__/Text.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
  website/static/css/components.css
  website/static/img/badge/badge--indicator.jpg
  website/static/img/badge/badge--mini.jpg
  website/static/img/badge/badge--standard.jpg
Labels: ✨Enhancement

#1554 fix: Hoist statics for withTheme hoc
  package.json
  src/config/withTheme.js
  yarn.lock
Labels: 💊 Bug Fix

#1575 Check to make sure that the SearchBar is really empty
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
Labels: 💊 Bug Fix

#1580 fix: Android SearchBar clear icon was using cancel icon
  src/searchbar/SearchBar-android.js
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: 💊 Bug Fix

#1582 feat: Add Image component
  docs/image.md
  src/image/Image.js
  src/image/__tests__/Image.js
  src/image/__tests__/__snapshots__/Image.js.snap
  src/index.d.ts
  src/index.js
  website/i18n/en.json
  website/sidebars.json
  website/static/css/components.css
Labels: 💡New Component

#1585 docs(website): Add onPageNav layout for website
  docs/button_group.md
  docs/card.md
  docs/checkbox.md
  docs/divider.md
  docs/header.md
  docs/icon.md
  docs/input.md
  docs/listitem.md
  docs/overlay.md
  docs/pricing.md
  docs/rating.md
  docs/searchbar.md
  docs/slider.md
  docs/social_icons.md
  docs/text.md
  docs/tile.md
  docs/tooltip.md
  website/siteConfig.js
  website/static/css/components.css
  website/static/css/custom.css
Labels: :book: Docs, ✨Enhancement

#1457 Add TextStyle to possible checkmark types.
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1587 feat(ButtonGroup): Add disabled styles
  docs/button_group.md
  src/buttons/ButtonGroup.js
  src/buttons/__tests__/ButtonGroup.js
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/index.d.ts
Labels: ✨Enhancement

#1592 fix(Avatar|Image): Fade out placeholder when image loads
  src/image/Image.js
  src/image/__tests__/__snapshots__/Image.js.snap
Labels: 💊 Bug Fix

#1599 fix: Remove eslint errors
  src/buttons/__tests__/ButtonGroup.js
  src/config/__tests__/ThemeProvider.js
  src/header/Header.js
  src/helpers/renderNode.js
  src/list/ListItem.js
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/tooltip/Tooltip.js
  src/tooltip/getTooltipCoordinate.js
Labels: 🔧 Tooling

#1601 test: Add lint to ci pipeline and pre-commit hook
  .travis.yml
  package.json
Labels: 🔧 Tooling

#1449 Add custom styles to iOS SearchBar cancel button
  docs/searchbar.md
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: ⏳Awaiting Reply, ✨Enhancement

#1621 test: Run default SearchBar tests that were omitted
  src/searchbar/__tests__/SearchBar-default.js
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
Labels: 🔧 Tooling

#1620 fix(SearchBar): Switch from material-community to material
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: ✨Enhancement

#1627 Fixed GitHub spelling
  website/pages/en/index.js
  website/siteConfig.js
  website/versioned_docs/version-0.19.1/contributing.md
Labels: :book: Docs
