Repository react-native-elements/react-native-elements, pull requests merged in 2018-02, with the labels that each got.

#896 Fixed default clearIcon name in docs for SearchBar component.
  docs/API/searchbar.md
Labels: docs

#930 Update README.md and remove useless md
  README.md
  default_installation.md
  using-with-crna-or-expo.md
Labels: Docs

#936 fix #934 - overlay image missing in docs website
  website/static/img/overlay.png
Labels: Docs

#916 Fix searchbar methods next
  docs/searchbar.md
  src/index.d.ts
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/SearchBar.js
  src/searchbar/__tests__/SearchBar-android.js
  src/searchbar/__tests__/SearchBar-default.js
  src/searchbar/__tests__/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: Bug Fix

#944 fix(header): Alignment on android now consistent with iOS
  src/header/Header.js
Labels: Bug Fix

#950 docs: Allow viewing `next` docs in version switch
  website/pages/en/versions.js
Labels: Docs, Enhancement

#951 add beta version to getting started
  website/versioned_docs/version-1.0.0-beta2/getting_started.md
Labels: Docs, Enhancement

#946 Adds header centerComponent alignment
  docs/header.md
  src/config/index.js
  src/config/statusBar.js
  src/header/Header.js
  src/header/__tests__/Header.js
  src/header/__tests__/__snapshots__/Header.js.snap
  src/index.d.ts
  website/pages/en/versions.js
  website/static/img/header-left.png
Labels: Enhancement

#943 [Button] Auto import LinearGradient if Expo
  src/buttons/Button.js
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: Enhancement

#953 Fixes #947 Input is not exported in TypeScript definitions
  src/index.d.ts
Labels: Types
