Repository react-native-elements/react-native-elements, pull requests merged in 2018-03, with the labels that each got.

#956 Fix styled-component for Input and Button
  src/buttons/Button.js
  src/input/Input.js
Labels: Bug Fix

#973 Fix website versioning
  website/pages/en/versions.js
Labels: Bug Fix, Docs

#982 Adds disabled and disabledStyle to Button
  src/buttons/Button.js
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: Enhancement

#974 Move Imgur images to GitHub
  .prettierignore
  README.md
  docs/badge.md
  docs/button.md
  docs/button_group.md
  docs/card.md
  docs/checkbox.md
  docs/forms.md
  docs/getting_started.md
  docs/icon.md
  docs/input.md
  docs/lists.md
  docs/pricing.md
  docs/rating.md
  docs/searchbar.md
  docs/social_icons.md
  docs/text.md
  website/static/img/badges.png
  website/static/img/button_group.png
  website/static/img/buttons.png
  website/static/img/buttons_0.19.png
  website/static/img/card.png
  website/static/img/checkbox.png
  website/static/img/forms_fields.png
  website/static/img/forms_validation.png
  website/static/img/icons.png
  website/static/img/input.png
  website/static/img/list-badges.jpeg
  website/static/img/lists.png
  website/static/img/peer-dep-error.png
  website/static/img/pricing.png
  website/static/img/rating_readonly.jpg
  website/static/img/searchbar.png
  website/static/img/social-icons.png
  website/static/img/text.png
  website/versioned_docs/version-0.19.0/badge.md
  website/versioned_docs/version-0.19.0/button.md
  website/versioned_docs/version-0.19.0/button_group.md
  website/versioned_docs/version-0.19.0/card.md
  website/versioned_docs/version-0.19.0/checkbox.md
  website/versioned_docs/version-0.19.0/forms.md
  website/versioned_docs/version-0.19.0/getting_started.md
  website/versioned_docs/version-0.19.0/icon.md
  website/versioned_docs/version-0.19.0/lists.md
  website/versioned_docs/version-0.19.0/pricing.md
  website/versioned_docs/version-0.19.0/rating.md
  website/versioned_docs/version-0.19.0/searchbar.md
  website/versioned_docs/version-0.19.0/social_icons.md
  website/versioned_docs/version-0.19.0/text.md
  website/versioned_docs/version-1.0.0-beta2/button.md
  website/versioned_docs/version-1.0.0-beta2/button_group.md
  website/versioned_docs/version-1.0.0-beta2/getting_started.md
  website/versioned_docs/version-1.0.0-beta2/input.md
  website/versioned_docs/version-1.0.0-beta2/searchbar.md
Labels: Bug Fix, Docs, WIP

#968 Allow title for Card to be a React Component (#918)
  src/card/Card.js
  src/card/__tests__/Card.js
  src/card/__tests__/__snapshots__/Card.js.snap
  src/index.d.ts
Labels: Enhancement

#983 docs(website): Better syntax colouring for code blocks
  website/package.json
  website/static/css/custom.css
  website/yarn.lock
Labels: Docs, Enhancement

#989 docs(1.0.0-beta2): Correct prop on Button to be text
  website/versioned_docs/version-1.0.0-beta2/button.md
Labels: Bug Fix, Docs

#995 Text default width
  src/buttons/Button.js
Labels: Bug Fix, v1

#1001 Update typings to match button title prop
  src/index.d.ts
Labels: Bug Fix, Types

#1007 Update typings to match Button title props
  src/index.d.ts
Labels: Bug Fix, Types

#1009 removed links and replaces JSX.Element React.ReactElement
  src/index.d.ts
Labels: Enhancement, Needs Response from Author, Types

#1003 feat(CheckBox): Allow custom component as Icon
  docs/checkbox.md
  src/checkbox/CheckBox.js
  src/checkbox/CheckBoxIcon.js
  src/checkbox/__tests__/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/index.d.ts
Labels: Enhancement

#986 Improve grammar and fix typos for some documents
  docs/contributing.md
  docs/icon.md
  docs/slider.md
  docs/testing.md
  website/versioned_docs/version-0.19.0/contributing.md
  website/versioned_docs/version-0.19.0/icon.md
  website/versioned_docs/version-0.19.0/slider.md
  website/versioned_docs/version-0.19.0/testing.md
  website/versioned_docs/version-1.0.0-beta3/contributing.md
Labels: Docs

#1033 Deploy automatically an example app on PRs
  .ci/expo-ci.sh
  .travis.yml
Labels: Tooling

#1043 Fix custom icon fonts example link
  docs/icon.md
Labels: Bug Fix, Docs

#999 Added containerStyle props for platform specific searchbars
  package-lock.json
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/SearchBar-android.js
  src/searchbar/__tests__/SearchBar-ios.js
  src/searchbar/__tests__/SearchBar.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
Labels: Enhancement

#1048 CI: The bot now modifies its own comment
  .ci/expo-ci.sh
  .ci/index.js
  .ci/package.json
Labels: WIP
