Repository react-native-elements/react-native-elements, pull requests merged in 2018-08, with the labels that each got.

#1299 Fixed <Input> bug that caused errorMessage and label to render an empty string outside of <Text>
  src/input/Input.js
Labels: 💊 Bug Fix

#1348 Expose wrapperStyle prop on Checkbox
  src/checkbox/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/index.d.ts
  website/versioned_docs/version-0.19.0/checkbox.md
Labels: ✨Enhancement

#1336 Accept 5.x of react-native-vector-icons
  package.json
Labels: 💊 Bug Fix

#1305 Hoist the isFocused() method from the react native input element
  src/index.d.ts
  src/input/Input.js
Labels: ✨Enhancement

#1342 Fixes #1341 add label props and error props for input
  docs/input.md
  src/index.d.ts
  src/input/Input.js
Labels: ✨Enhancement

#1357 (SearchBar) Allow containerStyle to override lightTheme styles
  src/searchbar/SearchBar-default.js
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
Labels: 💊 Bug Fix

#1361 fix: add missing "size" prop to CheckBox types
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1353 Do not use index as a key
  website/versioned_docs/version-0.19.0/lists.md
Labels: :book: Docs

#1390 docs(Button-0.19): Change fontSize type to number
  website/versioned_docs/version-0.19.0/button.md
Labels: :book: Docs, 💊 Bug Fix

#1397 docs(Tile 0.19): Fix imageSrc to use correct requires
  docs/tile.md
  website/versioned_docs/version-0.19.0/tile.md
Labels: :book: Docs, 💊 Bug Fix

#1366 feat(Icon): Add disabled and disabledStyle
  docs/icon.md
  src/header/__tests__/__snapshots__/NavButton.js.snap
  src/icons/Icon.js
  src/icons/__tests__/Icon.js
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/index.d.ts
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: ✨Enhancement

#1386 On start rating event
  docs/rating.md
  src/index.d.ts
  src/rating/Rating.js
Labels: ✨Enhancement

#1398 fix(ListItem): Don't display empty rightTitle or rightSubtitle
  src/list/ListItem.js
Labels: 💊 Bug Fix
