Repository react-native-elements/react-native-elements, pull requests merged in 2018-10, with the labels that each got.

#1448 Remove all references to `clearText`
  src/index.d.ts
  website/versioned_docs/version-1.0.0-beta2/searchbar.md
Labels: :book: Docs, ✨Enhancement, 🗂 Types

#1376 [docs] add left/right icon containers to readme
  docs/searchbar.md
Labels: :book: Docs

#1451 fix(types): Button correctly extend touchable props
  package.json
  src/index.d.ts
  yarn.lock
Labels: 💊 Bug Fix

#1458 Fix Header docs typo
  website/versioned_docs/version-1.0.0-beta6/header.md
Labels: :book: Docs, 💊 Bug Fix

#1462 1.0.0-beta7 - (Beta6 regression)
  package.json
  website/package.json
  website/versioned_docs/version-1.0.0-beta7/avatar.md
  website/versioned_docs/version-1.0.0-beta7/customization.md
  website/versioned_docs/version-1.0.0-beta7/header.md
  website/versioned_docs/version-1.0.0-beta7/icon.md
  website/versioned_docs/version-1.0.0-beta7/input.md
  website/versioned_docs/version-1.0.0-beta7/listitem.md
  website/versioned_docs/version-1.0.0-beta7/overview.md
  website/versioned_docs/version-1.0.0-beta7/pricing.md
  website/versioned_docs/version-1.0.0-beta7/rating.md
  website/versioned_docs/version-1.0.0-beta7/tooltip.md
  website/versions.json
Labels: 📦 RELEASE

#1466 fix(types): Correct type for ListItem component prop
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1468 fix(types): Allow partial theme be passed to ThemeProvider
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1476 docs: Change 0.19.0 to 0.19.1
  README.md
  website/pages/en/index.js
  website/siteConfig.js
  website/versioned_docs/version-0.19.1/avatar.md
  website/versioned_docs/version-0.19.1/badge.md
  website/versioned_docs/version-0.19.1/button.md
  website/versioned_docs/version-0.19.1/button_group.md
  website/versioned_docs/version-0.19.1/card.md
  website/versioned_docs/version-0.19.1/checkbox.md
  website/versioned_docs/version-0.19.1/contributing.md
  website/versioned_docs/version-0.19.1/customization.md
  website/versioned_docs/version-0.19.1/divider.md
  website/versioned_docs/version-0.19.1/forms.md
  website/versioned_docs/version-0.19.1/getting_started.md
  website/versioned_docs/version-0.19.1/header.md
  website/versioned_docs/version-0.19.1/icon.md
  website/versioned_docs/version-0.19.1/labels.md
  website/versioned_docs/version-0.19.1/lists.md
  website/versioned_docs/version-0.19.1/overview.md
  website/versioned_docs/version-0.19.1/pricing.md
  website/versioned_docs/version-0.19.1/rating.md
  website/versioned_docs/version-0.19.1/searchbar.md
  website/versioned_docs/version-0.19.1/slider.md
  website/versioned_docs/version-0.19.1/social_icons.md
  website/versioned_docs/version-0.19.1/testing.md
  website/versioned_docs/version-0.19.1/text.md
  website/versioned_docs/version-0.19.1/tile.md
  website/versioned_docs/version-0.19.1/troubleshooting.md
  website/versioned_sidebars/version-0.19.0-sidebars.json
  website/versioned_sidebars/version-0.19.1-sidebars.json
  website/versions.json
Labels: :book: Docs

#1479 Update component prop to Component
  docs/avatar.md
  docs/badge.md
  docs/button_group.md
  docs/checkbox.md
  docs/icon.md
  docs/listitem.md
  docs/social_icons.md
  src/avatar/Avatar.js
  src/badge/__tests__/badge.js
  src/badge/badge.js
  src/buttons/ButtonGroup.js
  src/checkbox/CheckBox.js
  src/checkbox/__tests__/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/icons/Icon.js
  src/index.d.ts
  src/list/ListItem.js
  src/social/SocialIcon.js
Labels: ✨Enhancement

#1488 fix(Avatar): Correct proptype for Avatar
  src/avatar/Avatar.js
Labels: 💊 Bug Fix

#1469 Use 'Must be greater than version' for RNVI dependency
  package.json
Labels: 💊 Bug Fix

#1489 Small Typo Fix on Getting Started Page
  docs/getting_started.md
Labels: :book: Docs, Hacktoberfest

#1503 Added a small call to action
  website/versioned_docs/version-0.19.1/overview.md
Labels: :book: Docs, Hacktoberfest

#1490 Made small updates to the prose at the top
  docs/overview.md
Labels: :book: Docs, Hacktoberfest

#1507 Change PropTypes to object to avoid the warning
  src/avatar/Avatar.js
Labels: 💊 Bug Fix

#1504 Fix failing tests on Windows
  package.json
  src/rating/__tests__/__snapshots__/Rating.js.snap
  yarn.lock
Labels: 💊 Bug Fix, 🔧 Tooling

#1518 docs(website): Update docusaurus to latest
  .eslintrc
  docs/getting_started.md
  website/i18n/en.json
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/siteConfig.js
  website/static/css/custom.css
  website/static/css/syntax.css
  website/static/css/toggler.css
  website/versioned_docs/version-0.19.1/getting_started.md
  website/versioned_docs/version-1.0.0-beta2/getting_started.md
  website/versioned_docs/version-1.0.0-beta3/getting_started.md
  website/versioned_sidebars/version-1.0.0-beta6-sidebars.json
  website/versioned_sidebars/version-1.0.0-beta7-sidebars.json
  website/yarn.lock
Labels: :book: Docs

#1523 fix: Change updateTheme to merge empty object first
  src/config/ThemeProvider.js
Labels: 💊 Bug Fix

#1526 docs(website): Add linear gradient usage section to Button docs
  docs/button.md
  website/versioned_docs/version-1.0.0-beta2/button.md
  website/versioned_docs/version-1.0.0-beta3/button.md
  website/versioned_docs/version-1.0.0-beta5/button.md
Labels: :book: Docs

#1527 docs(website): Add descriptions for every component
  docs/avatar.md
  docs/badge.md
  docs/button.md
  docs/button_group.md
  docs/card.md
  docs/checkbox.md
  docs/divider.md
  docs/header.md
  docs/icon.md
  docs/input.md
  docs/listitem.md
  docs/overlay.md
  docs/pricing.md
  docs/rating.md
  docs/searchbar.md
  docs/slider.md
  docs/social_icons.md
  docs/text.md
  docs/tile.md
  docs/tooltip.md
Labels: :book: Docs

#1510 feat(Tile): Allow caption to be a React element
  docs/tile.md
  src/tile/FeaturedTile.js
  src/tile/Tile.js
  src/tile/__tests__/FeaturedTile.js
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
Labels: ✨Enhancement

#1505 fix(Button): Make the padding consistent
  src/buttons/Button.js
  src/buttons/__tests__/__snapshots__/Button.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: 💊 Bug Fix

#1528 Remove expo ci from PRs
  .ci/expo-ci.sh
  .ci/index.js
  .ci/package.json
  .travis.yml
Labels: 🔧 Tooling

#1531 feat(Input): Allow label to be a React element
  docs/input.md
  src/input/Input.js
  src/input/__tests__/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
Labels: ✨Enhancement

#1532 docs(website): Add central place to show supported icon sets
  docs/avatar.md
  docs/checkbox.md
  docs/icon.md
  docs/tile.md
Labels: :book: Docs

#1529 Add AntDesign to icons in src/helps/getIconType.js
  docs/icon.md
  package.json
  src/helpers/getIconType.js
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/index.d.ts
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
  yarn.lock
Labels: ✨Enhancement

#1538 fix: Rounded buttons on android now work correctly
  src/buttons/Button.js
  src/buttons/__tests__/__snapshots__/Button.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: 💊 Bug Fix
