Repository react-native-elements/react-native-elements, pull requests merged in 2019-09, with the labels that each got.

#2048 docs: Add react-native-web usage
  docs/web_usage.md
  website/i18n/en.json
  website/sidebars.json
Labels: :book: Docs

#2049 feat: Export ThemeContext for usage with hooks
  docs/customization.md
  src/config/ThemeProvider.js
  src/config/index.js
  src/index.d.ts
  src/index.js
Labels: ✨Enhancement

#2050 fix: Regression with initial context value
  src/config/ThemeProvider.js
Labels: 💊 Bug Fix

#2051 fix(Image): Blank placeholder when source is null
  src/image/Image.js
Labels: 💊 Bug Fix

#2042 Update troubleshooting.md
  docs/troubleshooting.md
Labels: :book: Docs

#2052 Update customization.md
  docs/customization.md
Labels: :book: Docs

#2068 Remove containerBorderRadius props
  docs/button_group.md
  src/buttons/ButtonGroup.js
Labels: ✨Enhancement

#2079 fix: Revert Image to not use hooks
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/image/Image.js
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: 💊 Bug Fix

#2080 1.2.1
  package.json
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/image/Image.js
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: 📦 RELEASE

#2090 1.2.2
  package.json
  src/avatar/Avatar.js
  src/badge/Badge.js
  src/buttons/Button.js
  src/buttons/ButtonGroup.js
  src/checkbox/CheckBox.js
  src/header/Header.js
  src/icons/Icon.js
  src/image/Image.js
  src/list/ListItem.js
  src/social/SocialIcon.js
  src/tile/FeaturedTile.js
  src/tile/Tile.js
  yarn.lock
Labels: 📦 RELEASE

#2092 #2091 Honor testID if passed.
  src/image/Image.js
  src/image/__tests__/Image.js
Labels: 💊 Bug Fix

#2093 1.2.3
  .travis.yml
  package.json
  src/image/Image.js
  src/image/__tests__/Image.js
Labels: 📦 RELEASE

#2094 docs: Update README logo
  README.md
Labels: :book: Docs
