Repository react-native-elements/react-native-elements, pull requests merged in 2019-02, with the labels that each got.

#1745 fix missing comma typo in button docs
  docs/button.md
  website/versioned_docs/version-1.0.0/button.md
Labels: :book: Docs

#1741 ESLint error in Text.js Component
  src/text/Text.js
Labels: 💊 Bug Fix

#1749 Fix mix of import and module.exports
  src/helpers/normalizeText.js
Labels: ✨Enhancement

#1757 feat(CheckBox): Add titleProps prop
  docs/checkbox.md
  src/checkbox/CheckBox.js
  src/checkbox/__tests__/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/index.d.ts
Labels: ✨Enhancement

#1759 Fix PlaceholderContent type
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1763 Add Le Cheese to Showcase
  website/pages/en/index.js
Labels: :book: Docs

#1768 fix: add cancel method type for search bar
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1772 fix: Change merge library to deepmerge from lodash
  package.json
  src/config/ThemeProvider.js
  src/config/withTheme.js
  yarn.lock
Labels: 💊 Bug Fix

#1773 feat(Text): Add style props to customize header props
  docs/text.md
  src/index.d.ts
  src/text/Text.js
Labels: ✨Enhancement

#1769 fix: add underlayColor to SocialIconProps interface
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1777 Add List styling instructions
  website/blog/2019-01-27-1.0-release.md
Labels: :book: Docs

#1799 Fix button out of border ripple
  src/buttons/Button.js
Labels: 💊 Bug Fix

#1789 Update input.md
  docs/input.md
Labels: :book: Docs

#1739 Fixed false positioning of Slider Thumb
  src/slider/Slider.js
Labels: 💊 Bug Fix

#1802 v1.1.0
  docs/checkbox.md
  docs/customization.md
  docs/text.md
  package.json
  src/buttons/Button.js
  src/checkbox/CheckBox.js
  src/checkbox/__tests__/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/config/ThemeProvider.js
  src/config/withTheme.js
  src/helpers/normalizeText.js
  src/index.d.ts
  src/slider/Slider.js
  src/text/Text.js
  src/tooltip/Tooltip.js
  website/versioned_docs/version-1.0.0/customization.md
  yarn.lock
Labels: 📦 RELEASE
