Repository react-native-elements/react-native-elements, pull requests merged in 2019-07, with the labels that each got.

#1925 Update badge.md
  docs/badge.md
Labels: :book: Docs

#1934 Ignore folders from npm package
  .npmignore
Labels: 🔧 Tooling

#1941 ci: Simplify eslint setup
  .eslintrc
  .eslintrc.js
  .prettierrc
  package.json
  src/avatar/__tests__/Avatar.js
  src/buttons/Button.js
  src/buttons/ButtonGroup.js
  src/buttons/__tests__/Button.js
  src/checkbox/CheckBox.js
  src/config/__tests__/withTheme.js
  src/config/withTheme.js
  src/header/Header.js
  src/helpers/normalizeText.js
  src/index.js
  src/input/Input.js
  src/input/__tests__/Input.js
  src/slider/Slider.js
  src/social/SocialIcon.js
  src/tooltip/Tooltip.js
  src/tooltip/getTooltipCoordinate.js
  yarn.lock
Labels: 🔧 Tooling

#1942 Switch from `**` to `Math.pow` for getTooltipCoordinate
  src/tooltip/getTooltipCoordinate.js
Labels: 💊 Bug Fix

#1939 Corrected acheives spelling
  docs/customization.md
Labels: :book: Docs

#1911 fix #1897 , ImageSourcePropType
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#1818 Update social_icons.md
  docs/social_icons.md
Labels: :book: Docs

#1943 ci: Allow linting of typescript definitions
  .eslintignore
  package.json
  src/index.d.ts
  webpack.config.js
  yarn.lock
Labels: 🔧 Tooling

#1944 feat: Allow social icon type google
  docs/social_icons.md
  src/index.d.ts
  src/social/SocialIcon.js
Labels: ✨Enhancement

#1945 refactor: Cleanup some logic for SocialIcon
  src/social/SocialIcon.js
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
Labels: ✨Enhancement

#1948 Updated type definitions
  docs/tooltip.md
  src/index.d.ts
Labels: :book: Docs, 🗂 Types

#1955 improve documentation...
  docs/overlay.md
Labels: :book: Docs

#1956 fix(PricingCard): Correct text style proptypes
  src/pricing/PricingCard.js
Labels: 💊 Bug Fix

#1906 Add title style to pricing table button
  docs/pricing.md
  src/index.d.ts
  src/pricing/PricingCard.js
  src/pricing/__tests__/PricingCard.js
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: ✨Enhancement

#1914 Fix ButtonGroup color runtime exception
  src/buttons/ButtonGroup.js
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
Labels: 💊 Bug Fix

#1959 feat(types): Allow accessibility props on Icon
  src/index.d.ts
Labels: ✨Enhancement

#1961 fix(types): Allow ListItem to have TouchableHighlight props
  src/index.d.ts
Labels: 💊 Bug Fix

#1963 docs(Input): Change image to reflect actual component
  docs/input.md
  website/static/css/components.css
  website/static/img/input/input--label.png
  website/static/img/input/input--placeholder.png
Labels: :book: Docs

#1965 feat: Add testID to checkbox
  src/checkbox/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
Labels: ✨Enhancement

#1973 build: Remove webpack build files
  package.json
  webpack.config.js
  yarn.lock
Labels: 🔧 Tooling

#1974 Update tooltip.md
  docs/tooltip.md
Labels: :book: Docs

#1976 fix(Searchbar-ios): Contain text within cancel animation
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
Labels: 💊 Bug Fix

#1978 fix(SearchBar-ios): Hide clear icon on cancel
  src/searchbar/SearchBar-ios.js
Labels: 💊 Bug Fix

#1979 fix(SearchBar-ios): Stop layoutAnimation effects
  package.json
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/common.js
Labels: 💊 Bug Fix
