Repository react-native-elements/react-native-elements, pull requests merged in 2019-10, with the labels that each got.

#2100 fix: Remove props from native components
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/helpers/index.js
  src/input/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/text/Text.js
  src/text/__tests__/__snapshots__/Text.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: 💊 Bug Fix

#2101 1.2.4
  package.json
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/helpers/index.js
  src/input/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/text/Text.js
  src/text/__tests__/__snapshots__/Text.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: 📦 RELEASE

#2060 fix(Avatar): Unable to add border to avatar #2059
  src/avatar/Avatar.js
Labels: 💊 Bug Fix

#2105 fix(ListItem): Update PadView to work on web
  src/list/ListItem.js
Labels: 💊 Bug Fix

#2106 1.2.5
  package.json
  src/list/ListItem.js
Labels: 📦 RELEASE

#2109 New repo docs
  .github/CONTRIBUTING.MD
  .github/ISSUE_TEMPLATE/bug_report.md
  .travis.yml
  README.md
  docs/contributing.md
  docs/getting_started.md
  docs/icon.md
  docs/labels.md
  docs/troubleshooting.md
  package.json
  website/README.md
  website/blog/2019-01-27-1.0-release.md
  website/core/Footer.js
  website/pages/en/help.js
  website/pages/en/versions.js
  website/siteConfig.js
  website/versioned_docs/version-0.19.1/contributing.md
  website/versioned_docs/version-0.19.1/getting_started.md
  website/versioned_docs/version-0.19.1/header.md
  website/versioned_docs/version-0.19.1/icon.md
  website/versioned_docs/version-0.19.1/labels.md
  website/versioned_docs/version-0.19.1/troubleshooting.md
  website/versioned_docs/version-1.0.0/contributing.md
  website/versioned_docs/version-1.0.0/icon.md
  website/versioned_docs/version-1.2.0/getting_started.md
  website/versioned_docs/version-1.2.0/troubleshooting.md
Labels: :book: Docs, 👨‍💻WIP

#2119 chore: update and move types for react-native-vector-icons
  package.json
  yarn.lock
Labels: 💊 Bug Fix, 🗂 Types

#2112 added overlayContainerStyle to index.d.ts
  src/index.d.ts
Labels: 💊 Bug Fix

#2122 1.2.6
  package.json
  src/index.d.ts
  yarn.lock
Labels: 📦 RELEASE

#2123 Updates master with changes of new repo
  .github/CONTRIBUTING.MD
  .github/ISSUE_TEMPLATE/bug_report.md
  .travis.yml
  README.md
  docs/contributing.md
  docs/getting_started.md
  docs/icon.md
  docs/labels.md
  docs/troubleshooting.md
  package.json
  website/README.md
  website/blog/2019-01-27-1.0-release.md
  website/core/Footer.js
  website/pages/en/help.js
  website/pages/en/versions.js
  website/siteConfig.js
  website/versioned_docs/version-0.19.1/contributing.md
  website/versioned_docs/version-0.19.1/getting_started.md
  website/versioned_docs/version-0.19.1/header.md
  website/versioned_docs/version-0.19.1/icon.md
  website/versioned_docs/version-0.19.1/labels.md
  website/versioned_docs/version-0.19.1/troubleshooting.md
  website/versioned_docs/version-1.0.0/contributing.md
  website/versioned_docs/version-1.0.0/icon.md
  website/versioned_docs/version-1.2.0/getting_started.md
  website/versioned_docs/version-1.2.0/troubleshooting.md
Labels: :book: Docs

#2124 feat(Icon): Use platform Touchable
  src/icons/Icon.js
  src/icons/__tests__/Icon.js
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: ✨Enhancement

#2128 ci: Only deploy website changes from next
  .travis.yml
Labels: 🔧 Tooling

#2131 feat(Image): Add transition prop
  docs/image.md
  src/avatar/Avatar.js
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/image/Image.js
  src/image/__tests__/Image.js
  src/image/__tests__/__snapshots__/Image.js.snap
  src/index.d.ts
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: ✨Enhancement

#2138 feat(CheckBox): Improve accessibility
  src/checkbox/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
Labels: ✨Enhancement

#2142 feat(Icon): Add support for FontAwesome5
  docs/icon.md
  src/helpers/getIconType.js
  src/icons/Icon.js
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/index.d.ts
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: ✨Enhancement

#2137 Few fixes and Improvements for Button
  src/buttons/Button.js
  src/buttons/__tests__/__snapshots__/Button.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: ✨Enhancement

#2148 refactor: Cleanup Overlay
  docs/overlay.md
  src/index.d.ts
  src/overlay/Overlay.js
  src/overlay/__tests__/Overlay.js
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
Labels: ✨Enhancement

#2150 Add missing import to Text docs
  docs/text.md
Labels: :book: Docs

#2151 Overlay and Tooltip: add ModalComponent prop
  docs/overlay.md
  docs/tooltip.md
  docs/web_usage.md
  src/index.d.ts
  src/overlay/Overlay.js
  src/tooltip/Tooltip.js
Labels: ✨Enhancement

#1875 Tooltip: add new prop skipAndroidStatusBar for using inside RN Modal
  docs/tooltip.md
  src/index.d.ts
  src/tooltip/Tooltip.js
Labels: 💊 Bug Fix

#2155 fix(test): Exclude node_modules when running Jest #devcjog25
  package.json
Labels: 🔧 Tooling

#2147 fixed unnecessary ThemProps in withTheme hoc
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#2162 1.2.7
  package.json
  src/index.d.ts
Labels: 📦 RELEASE

#2160 fix(test): Add coveragePathIgnorePatterns property
  package.json
Labels: 🔧 Tooling

#2161 test: Increase code coverage for Tooltip component
  src/tooltip/__tests__/Tooltip.android.js
  src/tooltip/__tests__/Tooltip.js
  src/tooltip/__tests__/__snapshots__/Tooltip.js.snap
Labels: 🔧 Tooling

#2159 chore: Remove redundant syntaxes
  .travis.yml
Labels: 🔧 Tooling

#2144 Check whether loading is false before call onPress
  src/buttons/Button.js
  src/buttons/__tests__/Button.js
Labels: ✨Enhancement, 📞 Needs Response from Author

#2164 Update Onchangetext on input
  docs/input.md
Labels: :book: Docs
