Repository react-native-elements/react-native-elements, pull requests merged in 2019-04, with the labels that each got.

#1865 Update postinstall so that it doesn't cause failures
  package.json
Labels: 🔧 Tooling

#1867 fix(Text): Allow header styles to override bold styles
  src/text/Text.js
Labels: 💊 Bug Fix

#1873 feat(Tile): Add imageProps prop
  docs/tile.md
  src/index.d.ts
  src/tile/FeaturedTile.js
  src/tile/Tile.js
  src/tile/__tests__/FeaturedTile.js
  src/tile/__tests__/Tile.js
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: ✨Enhancement

#1874 feat(SearchBar): Allow default testID to be overridden
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
Labels: ✨Enhancement

#1869 Add overlayColor prop to toolTip for users to set the background color
  docs/tooltip.md
  src/index.d.ts
  src/tooltip/Tooltip.js
Labels: ✨Enhancement
