Repository react-native-elements/react-native-elements, pull requests merged in 2019-08, with the labels that each got.

#1891 Update header.md
  docs/header.md
Labels: :book: Docs

#1987 feat(Input): Remove shake as prop usage
  docs/input.md
  src/index.d.ts
  src/input/Input.js
  website/versioned_docs/version-1.0.0/input.md
  website/versioned_docs/version-1.1.0/input.md
Labels: :book: Docs, ✨Enhancement

#1839 feat: Support for linear-gradient in Header Component
  docs/header.md
  src/header/Header.js
  src/header/__tests__/Header.js
  src/index.d.ts
Labels: ✨Enhancement

#1988 feat(SocialIcon): Add new social networks
  docs/social_icons.md
  src/index.d.ts
  src/social/SocialIcon.js
Labels: ✨Enhancement

#1920 Added replaceTheme function
  docs/customization.md
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
  src/card/__tests__/__snapshots__/Card.js.snap
  src/config/ThemeProvider.js
  src/config/__tests__/ThemeProvider.js
  src/config/__tests__/__snapshots__/ThemeProvider.js.snap
  src/config/withTheme.js
  src/divider/__tests__/__snapshots__/Divider.js.snap
  src/header/__tests__/__snapshots__/Header.js.snap
  src/icons/__tests__/__snapshots__/Icon.js.snap
  src/image/__tests__/__snapshots__/Image.js.snap
  src/index.d.ts
  src/input/__tests__/__snapshots__/Input.js.snap
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/overlay/__tests__/__snapshots__/Overlay.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
  src/text/__tests__/__snapshots__/Text.js.snap
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: ✨Enhancement

#1991 chore: Bump packages in order to support hooks
  package.json
  src/card/__tests__/__snapshots__/Card.js.snap
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/image/__tests__/__snapshots__/Image.js.snap
  src/input/__tests__/__snapshots__/Input.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  yarn.lock
Labels: 🔧 Tooling

#1992 refactor: Base Image on ImageBackground
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/image/Image.js
  src/image/__tests__/Image.js
  src/image/__tests__/__snapshots__/Image.js.snap
Labels: ✨Enhancement

#1993 fix(Image): Allows interacting with children after load
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/image/Image.js
  src/image/__tests__/__snapshots__/Image.js.snap
Labels: 💊 Bug Fix

#1994 fix(ButtonGroup): Correct type for selectedIndex
  src/buttons/ButtonGroup.js
  src/index.d.ts
Labels: 💊 Bug Fix

#1996 Add disabled prop for Input component
  docs/input.md
  src/index.d.ts
  src/input/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: ✨Enhancement

#1835 feat: Update Card to use new Image Component
  src/card/Card.js
  src/card/__tests__/__snapshots__/Card.js.snap
Labels: ✨Enhancement

#1868 Add isEmpty check to onFocus of the Search Bar
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
Labels: 💊 Bug Fix

#1990 fix(Input): allow to pass React.forwardRef as inputComponent (#1901)
  package.json
  src/input/Input.js
Labels: 💊 Bug Fix

#1998 feat(Tile): Use RNE Image component
  src/tile/Tile.js
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: ✨Enhancement

#1999 feat(Image): Allow children to be displayed while image loads
  docs/avatar.md
  docs/card.md
  docs/image.md
  docs/tile.md
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
  src/image/Image.js
  src/image/__tests__/__snapshots__/Image.js.snap
  src/index.d.ts
  src/tile/FeaturedTile.js
  src/tile/Tile.js
  src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
  src/tile/__tests__/__snapshots__/Tile.js.snap
Labels: :book: Docs, ✨Enhancement, 🗂 Types

#2008 Added React.ComponentElement to input label type
  src/index.d.ts
Labels: 💊 Bug Fix, 🗂 Types

#2039 feat(SearchBar-ios): Add showCancel prop
  docs/searchbar.md
  src/index.d.ts
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
  website/i18n/en.json
Labels: ✨Enhancement
