Repository react-native-elements/react-native-elements, pull requests merged in 2019-01, with the labels that each got.

#1704 Added Showcase section to website
  package.json
  website/pages/en/index.js
  website/static/css/custom.css
Labels: :book: Docs, ✨Enhancement

#1708 fix(SearchBar iOS): Align margins closer to native searchbar
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
Labels: 💊 Bug Fix

#1718 fix(Avatar): Don't show placeholder style if not using source
  src/avatar/Avatar.js
  src/avatar/__tests__/Avatar.js
  src/avatar/__tests__/__snapshots__/Avatar.js.snap
Labels: 💊 Bug Fix

#1698 Slider flexbox layout
  src/slider/Slider.js
  src/slider/__tests__/Slider.js
  src/slider/__tests__/__snapshots__/Slider.js.snap
Labels: 💊 Bug Fix

#1720 fix(SearchBar|Input): Allow height on fields to scale with fontSize
  src/input/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: 💊 Bug Fix

#1728 feat(Divider): Allow passing view properties
  src/card/__tests__/__snapshots__/Card.js.snap
  src/divider/Divider.js
  src/divider/__tests__/Divider.js
  src/divider/__tests__/__snapshots__/Divider.js.snap
  src/index.d.ts
Labels: ✨Enhancement

#1723 1.0 Blog Post - Skeleton
  website/README.md
  website/blog/2019-01-27-1.0-release.md
Labels: :book: Docs

#1729 Update 2019-01-27-1.0-release.md
  website/blog/2019-01-27-1.0-release.md
Labels: :book: Docs

#1734 Fix small typo in customization docs
  docs/customization.md
Labels: :book: Docs, 💊 Bug Fix
