Repository react-native-elements/react-native-elements, pull requests merged in 2020-04, with the labels that each got.

#2316 Typo correction
  .github/CONTRIBUTING.MD
Labels: :book: Docs

#2254 Changing color of Facebook icon
  src/social/SocialIcon.js
  src/social/__tests__/__snapshots__/SocialIcon.js.snap
Labels: ✨Enhancement, 📞 Needs Response from Author

#1801 Fix: Height for errorMessage prop on Input
  docs/input.md
  src/index.d.ts
  src/input/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
  src/list/ListItem.js
  src/list/__tests__/__snapshots__/ListItem.js.snap
  src/searchbar/SearchBar-android.js
  src/searchbar/SearchBar-default.js
  src/searchbar/SearchBar-ios.js
  src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: ✨Enhancement, 👨‍💻WIP

#2116 fix: Change default left icon styles for input component
  src/input/Input.js
  src/input/__tests__/__snapshots__/Input.js.snap
  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Labels: 💊 Bug Fix

#2117 Update listitem.md
  docs/listitem.md
Labels: :book: Docs, 🤔Thoughts?

#2335 feat: Remove deprecated accessibilityStates
  src/buttons/Button.js
  src/buttons/__tests__/__snapshots__/Button.js.snap
  src/checkbox/CheckBox.js
  src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
  src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Labels: ✨Enhancement
