Repository react-native-elements/react-native-elements, pull requests merged in 2022-02, with the labels that each got.

#3335 fix(AirbnbRating): add props to parent component
  packages/base/src/AirbnbRating/AirbnbRating.tsx
Labels: PR: Bug Fix :bug:

#3074 feat(BottomSheet): add onBackdropPress handler
  example/src/views/bottomsheet.tsx
  packages/base/src/BottomSheet/BottomSheet.tsx
  packages/base/src/BottomSheet/__tests__/BottomSheet.test.tsx
  packages/base/src/BottomSheet/__tests__/__snapshots__/BottomSheet.test.tsx.snap
  website/docs/main/BottomSheet.mdx
Labels: PR: New Feature :tada:

#3354 docs(Icon): fix broken link
  website/versioned_docs/version-4.0.0-beta.0/main/Icon.md
Labels: PR: Docs :memo:
