Repository react-native-elements/react-native-elements, pull requests merged in 2022-05, with the labels that each got.

#3492 example: add webpack config
  example/App.tsx
  example/README.md
  example/app.json
  example/eas.json
  example/package.json
  example/src/components/header.tsx
  example/webpack.config.js
  package.json
  packages/base/package.json
  yarn.lock
Labels: Example App

#3504 fix(ListItem): custom Icon for Accordion
  example/src/views/lists2.tsx
  packages/base/src/ListItem/ListItem.Accordion.tsx
  packages/base/src/ListItem/__tests__/ListItem.test.tsx
  website/docs/components/ListItem.Accordion.mdx
Labels: PR: Bug Fix :bug:

#3505 fix(Tab): indicator on first render
  packages/base/src/Tab/Tab.tsx
Labels: PR: Bug Fix :bug:

#3506 docs: add fontWeight for Text on android
  packages/base/src/Text/Text.tsx
  scripts/docgen/generateMarkdown.ts
  scripts/docgen/mdx-template.hbs
  website/docs/component_usage/Text.mdx
  website/docs/components/AirbnbRating.mdx
  website/docs/components/Avatar.mdx
  website/docs/components/Badge.mdx
  website/docs/components/BottomSheet.mdx
  website/docs/components/Button.mdx
  website/docs/components/ButtonGroup.mdx
  website/docs/components/Card.mdx
  website/docs/components/CheckBox.mdx
  website/docs/components/Chip.mdx
  website/docs/components/Dialog.mdx
  website/docs/components/Divider.mdx
  website/docs/components/FAB.mdx
  website/docs/components/Header.mdx
  website/docs/components/Icon.mdx
  website/docs/components/Image.mdx
  website/docs/components/Input.mdx
  website/docs/components/LinearProgress.mdx
  website/docs/components/ListItem.Accordion.mdx
  website/docs/components/ListItem.Swipeable.mdx
  website/docs/components/ListItem.mdx
  website/docs/components/Overlay.mdx
  website/docs/components/PricingCard.mdx
  website/docs/components/Rating.mdx
  website/docs/components/SearchBar.mdx
  website/docs/components/Slider.mdx
  website/docs/components/SocialIcon.mdx
  website/docs/components/SpeedDial.mdx
  website/docs/components/Switch.mdx
  website/docs/components/Tab.mdx
  website/docs/components/TabView.mdx
  website/docs/components/Text.mdx
  website/docs/components/Tile.mdx
  website/docs/components/Tooltip.mdx
Labels: PR: Docs :memo:

#3514 fix(Dialog): Action button on web
  packages/base/src/Dialog/Dialog.Actions.tsx
Labels: PR: Bug Fix :bug:

#3534 fix(ListItem): left & right content width onRelease in Swipeable
  packages/base/src/ListItem/ListItem.Swipeable.tsx
Labels: PR: Bug Fix :bug:

#3536 docs: ThemeProvider code snippet
  website/docs/customization/1.themprovider.mdx
  website/versioned_docs/version-4.0.0-rc.3/customization/1.themprovider.mdx
Labels: PR: Docs :memo:

#3538 fix(Tab): inputRange using Array.from
  packages/base/src/Tab/Tab.tsx
  website/docs/components/Tab.mdx
Labels: PR: Bug Fix :bug:
