Repository react-native-elements/react-native-elements, pull requests merged in 2022-03, with the labels that each got.

#3372 fix(TabView): `disableSwipe` & `disableTransition` prop
  packages/base/src/TabView/TabView.tsx
  packages/base/src/TabView/__tests__/TabView.test.tsx
  website/docs/components/TabView.mdx
Labels: PR: New Feature :tada:

#3380 fix(TabView): swipe issue
  example/src/views/tabs.tsx
  example/src/views/whatsappClone.tsx
  packages/base/src/TabView/TabView.tsx
  website/docs/components/TabView.mdx
Labels: PR: Bug Fix :bug:

#3397 fix(Tab, TabView): conditional rendering
  packages/base/src/Tab/Tab.tsx
  packages/base/src/Tab/__tests__/Tab.test.tsx
  packages/base/src/TabView/TabView.tsx
  packages/base/src/TabView/__tests__/TabView.test.tsx
Labels: PR: Bug Fix :bug:

#3408 docs: add `styled-components` troubleshooting
  website/versioned_docs/version-3.4.2/troubleshooting.md
Labels: PR: Docs :memo:

#3324 feat(ThemeProvider)!: update withTheme and ThemeProvider
  lerna.json
  package.json
  packages/base/package.json
  packages/base/src/helpers/colors.ts
  packages/circular-slider/README.md
  packages/themed/src/config/ThemeProvider.tsx
  packages/themed/src/config/__tests__/ThemeProvider.test.tsx
  packages/themed/src/config/__tests__/withTheme.test.tsx
  packages/themed/src/config/colors.ts
  packages/themed/src/config/index.ts
  packages/themed/src/config/makeStyles.ts
  packages/themed/src/config/theme.ts
  packages/themed/src/config/withTheme.tsx
  packages/themed/src/index.ts
  website/docs/customization/color.mdx
  website/docs/customization/components.mdx
  website/docs/customization/overview.mdx
  website/docs/customization/pitfall.mdx
  website/docs/customization/theming.mdx
  website/docs/customization/typescript.mdx
  website/docs/migration-guide.md
  yarn.lock
Labels: PR: New Feature :tada:, PR: Breaking Change :boom:

#3416 docs: fix "colors" typo
  website/versioned_docs/version-4.0.0-rc.0/customization/color.mdx
Labels: PR: Docs :memo:
